### ISSUE TITLE
fixwindll.js searches for old napi version

### ISSUE THREAD

**Issue by bartbutenaers** [dceejay/tfjs-coco-ssd#15]
Hi @dceejay,

I have tried to install this node on my Windows 10 portable, however the installtion fails both via the flow editor palette failed and via command line.

Your post installation script raises following error:
```
> node-red-contrib-tfjs-coco-ssd@0.5.7 postinstall c:\Users\Gebruiker\.node-red\node_modules\node-red-contrib-tfjs-coco-ssd
> node fixwindll.js

The lib dll doesn't exist.
The dep dll exists
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, copyfile '../@tensorflow/tfjs-node/deps/lib/tensorflow.dll' -> '../@tensorflow/tfjs-node/lib/napi-v5/tensorflow.dll'
    at Object.copyFileSync (fs.js:1904:3)
    at Object.<anonymous> (c:\Users\Gebruiker\.node-red\node_modules\node-red-contrib-tfjs-coco-ssd\fixwindll.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '../@tensorflow/tfjs-node/deps/lib/tensorflow.dll',
  dest: '../@tensorflow/tfjs-node/lib/napi-v5/tensorflow.dll'
```

Seems that your script searches for _**napi-v5**_, while on my filesystem there is only a _**napi-v7**_:

![image](https://user-images.githubusercontent.com/14224149/141250953-790ada41-e850-4178-863e-8b5ebacfd164.png)

Would be very nice if you could fix this.

Thanks !!!!!!!
Bart

**Comment by dceejay** [comment]
so yes - time moves on... versions change...
but I see the dll is already there ? or did you move it manually ?
(If it's now already in correct place I won't have to patch it...)

**Comment by bartbutenaers** [comment]
Yes Dave,
indeed the tensorflow.dll file was already there.   I have ***NOT*** moved anything manually.
But as you can see it even fails when that file is already there...

**Comment by dceejay** [comment]
well all that is failing is me copying the file to the wrong place...  as long as it's there then the library will work...

**Comment by bartbutenaers** [comment]
But when it fails I don't get your node in my pallette.

**Comment by dceejay** [comment]
ah ok
