### ISSUE TITLE
Error: marker was not found when sending jpg path

### ISSUE THREAD

**Issue by philipzimmermann** [dceejay/tfjs-coco-ssd#18]
I'm getting below error when saving a jpg image to disk and passing the file path to the coco node. Strangely it works the first time after starting the flow but after that the error occurs on every call. Any suggestions?

    (node:124290) UnhandledPromiseRejectionWarning: Error: marker was not found
        at decodeScan (/home/philip/.node-red/node_modules/jpeg-js/lib/decoder.js:344:15)
        at constructor.parse (/home/philip/.node-red/node_modules/jpeg-js/lib/decoder.js:805:29)
        at Object.decode (/home/philip/.node-red/node_modules/jpeg-js/lib/decoder.js:1109:11)
        at reco (/home/philip/.node-red/node_modules/node-red-contrib-tfjs-coco-ssd/tfjs.js:57:57)
        at TensorFlowCoCo._inputCallback (/home/philip/.node-red/node_modules/node-red-contrib-tfjs-coco-ssd/tfjs.js:111:21)
        at hooks.trigger (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:204:26)
        at Object.trigger (/usr/local/lib/node_modules/node-red/node_modules/@node-red/util/lib/hooks.js:149:13)
        at TensorFlowCoCo.Node._emitInput (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:196:11)
        at TensorFlowCoCo.Node.emit (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:180:25)
        at TensorFlowCoCo.Node.receive (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:479:10)
    (node:124290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

**Comment by dceejay** [comment]
can you share a small example flow that shows how you are doing this ? Thanks
