### ISSUE TITLE
Can't install on raspberry pi running Bullseye 64 bit

### ISSUE THREAD

**Issue by crxporter** [dceejay/tfjs-coco-ssd#22]
I'm just learning today as I upgrade all my things to Bullseye that libtensorflow is not built for Bullseye 64 bit. I'm attaching the error log below - which is the same as if I try installing with `npm i @tensorflow/tfjs-node`

I know this isn't your package, but do you know where I could find a list of supported systems? Mainly, do I need to go back to Buster 32 bit or will Bullseye 32 bit work? I was searching in the tfjs-node repo for a bit and couldn't find any list like that.

Background: I'm rebuilding my pi disk image. Previously this nodered contrib worked great on the same pi while running Buster 32 bit.

```
-----------------------------------------------------------
2022-05-17T11:54:23.067Z Install : node-red-contrib-tfjs-coco-ssd 1.0.3

2022-05-17T11:54:23.186Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-tfjs-coco-ssd@1.0.3
2022-05-17T11:55:01.944Z [err] npm
2022-05-17T11:55:01.944Z [err]  ERR! code 1
2022-05-17T11:55:01.944Z [err] npm ERR! path /home/gporter/.node-red/node_modules/@tensorflow/tfjs-node
2022-05-17T11:55:01.949Z [err] npm ERR!
2022-05-17T11:55:01.949Z [err]  command failed
2022-05-17T11:55:01.949Z [err] npm ERR! command sh -c node scripts/install.js
2022-05-17T11:55:01.949Z [err] npm ERR!
2022-05-17T11:55:01.950Z [err]  CPU-linux-3.17.0.tar.gz
2022-05-17T11:55:01.950Z [err] npm ERR! * Downloading libtensorflow
2022-05-17T11:55:01.950Z [err] npm ERR! /home/gporter/.node-red/node_modules/@tensorflow/tfjs-node/scripts/install.js:106
2022-05-17T11:55:01.950Z [err] npm 
2022-05-17T11:55:01.950Z [err] ERR!     throw new Error(`Unsupported system: ${libType}-${platform}-${os.arch()}`);
2022-05-17T11:55:01.950Z [err] npm ERR!           ^
2022-05-17T11:55:01.950Z [err] npm
2022-05-17T11:55:01.950Z [err]  ERR! 
2022-05-17T11:55:01.950Z [err] npm ERR!
2022-05-17T11:55:01.950Z [err]  Error: Unsupported system: cpu-linux-arm64
2022-05-17T11:55:01.950Z [err] npm ERR!     at getPlatformLibtensorflowUri (/home/gporter/.node-red/node_modules/@tensorflow/tfjs-node/scripts/install.js:106:11)
2022-05-17T11:55:01.950Z [err] npm
2022-05-17T11:55:01.951Z [err]  ERR!     at downloadLibtensorflow (/home/gporter/.node-red/node_modules/@tensorflow/tfjs-node/scripts/install.js:139:15)
2022-05-17T11:55:01.951Z [err] npm ERR!     at async run (/home/gporter/.node-red/node_modules/@tensorflow/tfjs-node/scripts/install.js:208:5)
2022-05-17T11:55:01.955Z [err] 
2022-05-17T11:55:01.956Z [err] npm 
2022-05-17T11:55:01.956Z [err] ERR! A complete log of this run can be found in:
2022-05-17T11:55:01.956Z [err] npm ERR!     /home/gporter/.npm/_logs/2022-05-17T11_54_23_714Z-debug-0.log
2022-05-17T11:55:01.997Z rc=1
```

**Comment by dceejay** [comment]
Must admit not tried it on 64bit Rapsbian... did you try following the readme to rebuild on the Pi ?
https://www.npmjs.com/package/@tensorflow/tfjs-node

**Comment by crxporter** [comment]
I had not tried the rebuild command before. But now I have, it didn't help.

The rebuild is apparently for after it's been installed but I can't get through the install. 


Next question: have you tried on 32 bit bullseye (debian 11)? That'll be my next attempt before I bump back to buster.

**Comment by crxporter** [comment]
As expected, the install went just fine on Bullseye 32 bit.

But now I have the issue mentioned here #20 

Closing this one with the assumption that tensorflow js is not ready for 64 bits. 

I'll continue troubleshooting on the other issue.
